apiVersion: v2
name: truenas-csi
description: Kubernetes CSI driver for TrueNAS SCALE storage
type: application
version: 4.0.0
appVersion: "4.0.0"
kubeVersion: ">=1.20.0-0"
home: https://github.com/GizmoTickler/truenas-scale-csi
sources:
  - https://github.com/GizmoTickler/truenas-scale-csi
maintainers:
  - name: GizmoTickler
keywords:
  - storage
  - csi
  - truenas
  - zfs
  - nfs
  - iscsi
  - nvme
